version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    volumes:
      - .:/app
