version: "3"

services:
  web:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    volumes:
      - .:/app