
version: "3"


services:
  # Servicio web
  web:
   
    build: .
     
      dockerfile: Dockerfile
    restart: always
 
    ports:
      - "5000:5000"
   
    environment:
      - FLASK_APP=app.py
   
    volumes:
      - .:/app
